// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GRPCMsg.proto

package com.homvee.grpc.service.msgs;

public final class GRPCMsg {
  private GRPCMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TeacherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.homvee.grpc.Teacher)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 32;</code>
     */
    long getId();

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 age = 5;</code>
     */
    int getAge();

    /**
     * <code>optional float salary = 6;</code>
     */
    float getSalary();

    /**
     * <code>repeated .com.homvee.grpc.Student students = 2;</code>
     */
    java.util.List<com.homvee.grpc.service.msgs.GRPCMsg.Student> 
        getStudentsList();
    /**
     * <code>repeated .com.homvee.grpc.Student students = 2;</code>
     */
    com.homvee.grpc.service.msgs.GRPCMsg.Student getStudents(int index);
    /**
     * <code>repeated .com.homvee.grpc.Student students = 2;</code>
     */
    int getStudentsCount();
    /**
     * <code>repeated .com.homvee.grpc.Student students = 2;</code>
     */
    java.util.List<? extends com.homvee.grpc.service.msgs.GRPCMsg.StudentOrBuilder> 
        getStudentsOrBuilderList();
    /**
     * <code>repeated .com.homvee.grpc.Student students = 2;</code>
     */
    com.homvee.grpc.service.msgs.GRPCMsg.StudentOrBuilder getStudentsOrBuilder(
        int index);

    /**
     * <code>map&lt;string, .com.homvee.grpc.Course&gt; courseTcher = 11;</code>
     */
    java.util.Map<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course>
    getCourseTcher();
  }
  /**
   * Protobuf type {@code com.homvee.grpc.Teacher}
   */
  public  static final class Teacher extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.homvee.grpc.Teacher)
      TeacherOrBuilder {
    // Use Teacher.newBuilder() to construct.
    private Teacher(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Teacher() {
      id_ = 0L;
      name_ = "";
      age_ = 0;
      salary_ = 0F;
      students_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Teacher(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                students_ = new java.util.ArrayList<com.homvee.grpc.service.msgs.GRPCMsg.Student>();
                mutable_bitField0_ |= 0x00000010;
              }
              students_.add(input.readMessage(com.homvee.grpc.service.msgs.GRPCMsg.Student.parser(), extensionRegistry));
              break;
            }
            case 40: {

              age_ = input.readInt32();
              break;
            }
            case 53: {

              salary_ = input.readFloat();
              break;
            }
            case 90: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                courseTcher_ = com.google.protobuf.MapField.newMapField(
                    CourseTcherDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000020;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course>
              courseTcher = input.readMessage(
                  CourseTcherDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              courseTcher_.getMutableMap().put(courseTcher.getKey(), courseTcher.getValue());
              break;
            }
            case 256: {

              id_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          students_ = java.util.Collections.unmodifiableList(students_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Teacher_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 11:
          return internalGetCourseTcher();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Teacher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.homvee.grpc.service.msgs.GRPCMsg.Teacher.class, com.homvee.grpc.service.msgs.GRPCMsg.Teacher.Builder.class);
    }

    /**
     * Protobuf enum {@code com.homvee.grpc.Teacher.Gender}
     */
    public enum Gender
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKOWN = 0;</code>
       */
      UNKOWN(0, 0),
      /**
       * <code>MALE = 1;</code>
       */
      MALE(1, 1),
      /**
       * <code>FEMALE = 2;</code>
       */
      FEMALE(2, 2),
      UNRECOGNIZED(-1, -1),
      ;

      /**
       * <code>UNKOWN = 0;</code>
       */
      public static final int UNKOWN_VALUE = 0;
      /**
       * <code>MALE = 1;</code>
       */
      public static final int MALE_VALUE = 1;
      /**
       * <code>FEMALE = 2;</code>
       */
      public static final int FEMALE_VALUE = 2;


      public final int getNumber() {
        if (index == -1) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      public static Gender valueOf(int value) {
        switch (value) {
          case 0: return UNKOWN;
          case 1: return MALE;
          case 2: return FEMALE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Gender>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Gender> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
              public Gender findValueByNumber(int number) {
                return Gender.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.homvee.grpc.service.msgs.GRPCMsg.Teacher.getDescriptor().getEnumTypes().get(0);
      }

      private static final Gender[] VALUES = values();

      public static Gender valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Gender(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.homvee.grpc.Teacher.Gender)
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 32;
    private long id_;
    /**
     * <code>optional int64 id = 32;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 5;
    private int age_;
    /**
     * <code>optional int32 age = 5;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int SALARY_FIELD_NUMBER = 6;
    private float salary_;
    /**
     * <code>optional float salary = 6;</code>
     */
    public float getSalary() {
      return salary_;
    }

    public static final int STUDENTS_FIELD_NUMBER = 2;
    private java.util.List<com.homvee.grpc.service.msgs.GRPCMsg.Student> students_;
    /**
     * <code>repeated .com.homvee.grpc.Student students = 2;</code>
     */
    public java.util.List<com.homvee.grpc.service.msgs.GRPCMsg.Student> getStudentsList() {
      return students_;
    }
    /**
     * <code>repeated .com.homvee.grpc.Student students = 2;</code>
     */
    public java.util.List<? extends com.homvee.grpc.service.msgs.GRPCMsg.StudentOrBuilder> 
        getStudentsOrBuilderList() {
      return students_;
    }
    /**
     * <code>repeated .com.homvee.grpc.Student students = 2;</code>
     */
    public int getStudentsCount() {
      return students_.size();
    }
    /**
     * <code>repeated .com.homvee.grpc.Student students = 2;</code>
     */
    public com.homvee.grpc.service.msgs.GRPCMsg.Student getStudents(int index) {
      return students_.get(index);
    }
    /**
     * <code>repeated .com.homvee.grpc.Student students = 2;</code>
     */
    public com.homvee.grpc.service.msgs.GRPCMsg.StudentOrBuilder getStudentsOrBuilder(
        int index) {
      return students_.get(index);
    }

    public static final int COURSETCHER_FIELD_NUMBER = 11;
    private static final class CourseTcherDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course>newDefaultInstance(
                  com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Teacher_CourseTcherEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.homvee.grpc.service.msgs.GRPCMsg.Course.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course> courseTcher_;
    private com.google.protobuf.MapField<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course>
    internalGetCourseTcher() {
      if (courseTcher_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CourseTcherDefaultEntryHolder.defaultEntry);
     }
      return courseTcher_;
    }
    /**
     * <code>map&lt;string, .com.homvee.grpc.Course&gt; courseTcher = 11;</code>
     */

    public java.util.Map<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course> getCourseTcher() {
      return internalGetCourseTcher().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      for (int i = 0; i < students_.size(); i++) {
        output.writeMessage(2, students_.get(i));
      }
      if (age_ != 0) {
        output.writeInt32(5, age_);
      }
      if (salary_ != 0F) {
        output.writeFloat(6, salary_);
      }
      for (java.util.Map.Entry<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course> entry
           : internalGetCourseTcher().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course>
        courseTcher = CourseTcherDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(11, courseTcher);
      }
      if (id_ != 0L) {
        output.writeInt64(32, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      for (int i = 0; i < students_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, students_.get(i));
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, age_);
      }
      if (salary_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, salary_);
      }
      for (java.util.Map.Entry<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course> entry
           : internalGetCourseTcher().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course>
        courseTcher = CourseTcherDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(11, courseTcher);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(32, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.homvee.grpc.service.msgs.GRPCMsg.Teacher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Teacher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Teacher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Teacher parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Teacher parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Teacher parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Teacher parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Teacher parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.homvee.grpc.service.msgs.GRPCMsg.Teacher prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.homvee.grpc.Teacher}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.homvee.grpc.Teacher)
        com.homvee.grpc.service.msgs.GRPCMsg.TeacherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Teacher_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 11:
            return internalGetCourseTcher();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 11:
            return internalGetMutableCourseTcher();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Teacher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.homvee.grpc.service.msgs.GRPCMsg.Teacher.class, com.homvee.grpc.service.msgs.GRPCMsg.Teacher.Builder.class);
      }

      // Construct using com.homvee.grpc.service.msgs.GRPCMsg.Teacher.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getStudentsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        age_ = 0;

        salary_ = 0F;

        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          studentsBuilder_.clear();
        }
        internalGetMutableCourseTcher().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Teacher_descriptor;
      }

      public com.homvee.grpc.service.msgs.GRPCMsg.Teacher getDefaultInstanceForType() {
        return com.homvee.grpc.service.msgs.GRPCMsg.Teacher.getDefaultInstance();
      }

      public com.homvee.grpc.service.msgs.GRPCMsg.Teacher build() {
        com.homvee.grpc.service.msgs.GRPCMsg.Teacher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.homvee.grpc.service.msgs.GRPCMsg.Teacher buildPartial() {
        com.homvee.grpc.service.msgs.GRPCMsg.Teacher result = new com.homvee.grpc.service.msgs.GRPCMsg.Teacher(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        result.age_ = age_;
        result.salary_ = salary_;
        if (studentsBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            students_ = java.util.Collections.unmodifiableList(students_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.students_ = students_;
        } else {
          result.students_ = studentsBuilder_.build();
        }
        result.courseTcher_ = internalGetCourseTcher();
        result.courseTcher_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.homvee.grpc.service.msgs.GRPCMsg.Teacher) {
          return mergeFrom((com.homvee.grpc.service.msgs.GRPCMsg.Teacher)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.homvee.grpc.service.msgs.GRPCMsg.Teacher other) {
        if (other == com.homvee.grpc.service.msgs.GRPCMsg.Teacher.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getSalary() != 0F) {
          setSalary(other.getSalary());
        }
        if (studentsBuilder_ == null) {
          if (!other.students_.isEmpty()) {
            if (students_.isEmpty()) {
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureStudentsIsMutable();
              students_.addAll(other.students_);
            }
            onChanged();
          }
        } else {
          if (!other.students_.isEmpty()) {
            if (studentsBuilder_.isEmpty()) {
              studentsBuilder_.dispose();
              studentsBuilder_ = null;
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000010);
              studentsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getStudentsFieldBuilder() : null;
            } else {
              studentsBuilder_.addAllMessages(other.students_);
            }
          }
        }
        internalGetMutableCourseTcher().mergeFrom(
            other.internalGetCourseTcher());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.homvee.grpc.service.msgs.GRPCMsg.Teacher parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.homvee.grpc.service.msgs.GRPCMsg.Teacher) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 id = 32;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 32;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 32;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>optional int32 age = 5;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>optional int32 age = 5;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 age = 5;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private float salary_ ;
      /**
       * <code>optional float salary = 6;</code>
       */
      public float getSalary() {
        return salary_;
      }
      /**
       * <code>optional float salary = 6;</code>
       */
      public Builder setSalary(float value) {
        
        salary_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float salary = 6;</code>
       */
      public Builder clearSalary() {
        
        salary_ = 0F;
        onChanged();
        return this;
      }

      private java.util.List<com.homvee.grpc.service.msgs.GRPCMsg.Student> students_ =
        java.util.Collections.emptyList();
      private void ensureStudentsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          students_ = new java.util.ArrayList<com.homvee.grpc.service.msgs.GRPCMsg.Student>(students_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.homvee.grpc.service.msgs.GRPCMsg.Student, com.homvee.grpc.service.msgs.GRPCMsg.Student.Builder, com.homvee.grpc.service.msgs.GRPCMsg.StudentOrBuilder> studentsBuilder_;

      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public java.util.List<com.homvee.grpc.service.msgs.GRPCMsg.Student> getStudentsList() {
        if (studentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(students_);
        } else {
          return studentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public int getStudentsCount() {
        if (studentsBuilder_ == null) {
          return students_.size();
        } else {
          return studentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public com.homvee.grpc.service.msgs.GRPCMsg.Student getStudents(int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);
        } else {
          return studentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public Builder setStudents(
          int index, com.homvee.grpc.service.msgs.GRPCMsg.Student value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.set(index, value);
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public Builder setStudents(
          int index, com.homvee.grpc.service.msgs.GRPCMsg.Student.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.set(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public Builder addStudents(com.homvee.grpc.service.msgs.GRPCMsg.Student value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public Builder addStudents(
          int index, com.homvee.grpc.service.msgs.GRPCMsg.Student value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(index, value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public Builder addStudents(
          com.homvee.grpc.service.msgs.GRPCMsg.Student.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public Builder addStudents(
          int index, com.homvee.grpc.service.msgs.GRPCMsg.Student.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public Builder addAllStudents(
          java.lang.Iterable<? extends com.homvee.grpc.service.msgs.GRPCMsg.Student> values) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, students_);
          onChanged();
        } else {
          studentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public Builder clearStudents() {
        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          studentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public Builder removeStudents(int index) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.remove(index);
          onChanged();
        } else {
          studentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public com.homvee.grpc.service.msgs.GRPCMsg.Student.Builder getStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public com.homvee.grpc.service.msgs.GRPCMsg.StudentOrBuilder getStudentsOrBuilder(
          int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);  } else {
          return studentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public java.util.List<? extends com.homvee.grpc.service.msgs.GRPCMsg.StudentOrBuilder> 
           getStudentsOrBuilderList() {
        if (studentsBuilder_ != null) {
          return studentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(students_);
        }
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public com.homvee.grpc.service.msgs.GRPCMsg.Student.Builder addStudentsBuilder() {
        return getStudentsFieldBuilder().addBuilder(
            com.homvee.grpc.service.msgs.GRPCMsg.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public com.homvee.grpc.service.msgs.GRPCMsg.Student.Builder addStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().addBuilder(
            index, com.homvee.grpc.service.msgs.GRPCMsg.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .com.homvee.grpc.Student students = 2;</code>
       */
      public java.util.List<com.homvee.grpc.service.msgs.GRPCMsg.Student.Builder> 
           getStudentsBuilderList() {
        return getStudentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.homvee.grpc.service.msgs.GRPCMsg.Student, com.homvee.grpc.service.msgs.GRPCMsg.Student.Builder, com.homvee.grpc.service.msgs.GRPCMsg.StudentOrBuilder> 
          getStudentsFieldBuilder() {
        if (studentsBuilder_ == null) {
          studentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.homvee.grpc.service.msgs.GRPCMsg.Student, com.homvee.grpc.service.msgs.GRPCMsg.Student.Builder, com.homvee.grpc.service.msgs.GRPCMsg.StudentOrBuilder>(
                  students_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          students_ = null;
        }
        return studentsBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course> courseTcher_;
      private com.google.protobuf.MapField<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course>
      internalGetCourseTcher() {
        if (courseTcher_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CourseTcherDefaultEntryHolder.defaultEntry);
       }
        return courseTcher_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course>
      internalGetMutableCourseTcher() {
        onChanged();;
        if (courseTcher_ == null) {
          courseTcher_ = com.google.protobuf.MapField.newMapField(
              CourseTcherDefaultEntryHolder.defaultEntry);
        }
        if (!courseTcher_.isMutable()) {
          courseTcher_ = courseTcher_.copy();
        }
        return courseTcher_;
      }
      /**
       * <code>map&lt;string, .com.homvee.grpc.Course&gt; courseTcher = 11;</code>
       */
      public java.util.Map<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course> getCourseTcher() {
        return internalGetCourseTcher().getMap();
      }
      /**
       * <code>map&lt;string, .com.homvee.grpc.Course&gt; courseTcher = 11;</code>
       */
      public java.util.Map<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course>
      getMutableCourseTcher() {
        return internalGetMutableCourseTcher().getMutableMap();
      }
      /**
       * <code>map&lt;string, .com.homvee.grpc.Course&gt; courseTcher = 11;</code>
       */
      public Builder putAllCourseTcher(
          java.util.Map<java.lang.String, com.homvee.grpc.service.msgs.GRPCMsg.Course> values) {
        getMutableCourseTcher().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.homvee.grpc.Teacher)
    }

    // @@protoc_insertion_point(class_scope:com.homvee.grpc.Teacher)
    private static final com.homvee.grpc.service.msgs.GRPCMsg.Teacher DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.homvee.grpc.service.msgs.GRPCMsg.Teacher();
    }

    public static com.homvee.grpc.service.msgs.GRPCMsg.Teacher getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Teacher>
        PARSER = new com.google.protobuf.AbstractParser<Teacher>() {
      public Teacher parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Teacher(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Teacher> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Teacher> getParserForType() {
      return PARSER;
    }

    public com.homvee.grpc.service.msgs.GRPCMsg.Teacher getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.homvee.grpc.Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 7;</code>
     */
    long getId();

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
     */
    java.util.List<com.homvee.grpc.service.msgs.GRPCMsg.Course> 
        getCoursesList();
    /**
     * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
     */
    com.homvee.grpc.service.msgs.GRPCMsg.Course getCourses(int index);
    /**
     * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
     */
    int getCoursesCount();
    /**
     * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
     */
    java.util.List<? extends com.homvee.grpc.service.msgs.GRPCMsg.CourseOrBuilder> 
        getCoursesOrBuilderList();
    /**
     * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
     */
    com.homvee.grpc.service.msgs.GRPCMsg.CourseOrBuilder getCoursesOrBuilder(
        int index);

    /**
     * <code>repeated string sports = 3;</code>
     */
    com.google.protobuf.ProtocolStringList
        getSportsList();
    /**
     * <code>repeated string sports = 3;</code>
     */
    int getSportsCount();
    /**
     * <code>repeated string sports = 3;</code>
     */
    java.lang.String getSports(int index);
    /**
     * <code>repeated string sports = 3;</code>
     */
    com.google.protobuf.ByteString
        getSportsBytes(int index);
  }
  /**
   * Protobuf type {@code com.homvee.grpc.Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.homvee.grpc.Student)
      StudentOrBuilder {
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      id_ = 0L;
      name_ = "";
      courses_ = java.util.Collections.emptyList();
      sports_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                courses_ = new java.util.ArrayList<com.homvee.grpc.service.msgs.GRPCMsg.Course>();
                mutable_bitField0_ |= 0x00000004;
              }
              courses_.add(input.readMessage(com.homvee.grpc.service.msgs.GRPCMsg.Course.parser(), extensionRegistry));
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                sports_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              sports_.add(s);
              break;
            }
            case 56: {

              id_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          courses_ = java.util.Collections.unmodifiableList(courses_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          sports_ = sports_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Student_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.homvee.grpc.service.msgs.GRPCMsg.Student.class, com.homvee.grpc.service.msgs.GRPCMsg.Student.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 7;
    private long id_;
    /**
     * <code>optional int64 id = 7;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COURSES_FIELD_NUMBER = 2;
    private java.util.List<com.homvee.grpc.service.msgs.GRPCMsg.Course> courses_;
    /**
     * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
     */
    public java.util.List<com.homvee.grpc.service.msgs.GRPCMsg.Course> getCoursesList() {
      return courses_;
    }
    /**
     * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
     */
    public java.util.List<? extends com.homvee.grpc.service.msgs.GRPCMsg.CourseOrBuilder> 
        getCoursesOrBuilderList() {
      return courses_;
    }
    /**
     * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
     */
    public int getCoursesCount() {
      return courses_.size();
    }
    /**
     * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
     */
    public com.homvee.grpc.service.msgs.GRPCMsg.Course getCourses(int index) {
      return courses_.get(index);
    }
    /**
     * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
     */
    public com.homvee.grpc.service.msgs.GRPCMsg.CourseOrBuilder getCoursesOrBuilder(
        int index) {
      return courses_.get(index);
    }

    public static final int SPORTS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList sports_;
    /**
     * <code>repeated string sports = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getSportsList() {
      return sports_;
    }
    /**
     * <code>repeated string sports = 3;</code>
     */
    public int getSportsCount() {
      return sports_.size();
    }
    /**
     * <code>repeated string sports = 3;</code>
     */
    public java.lang.String getSports(int index) {
      return sports_.get(index);
    }
    /**
     * <code>repeated string sports = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSportsBytes(int index) {
      return sports_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      for (int i = 0; i < courses_.size(); i++) {
        output.writeMessage(2, courses_.get(i));
      }
      for (int i = 0; i < sports_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, sports_.getRaw(i));
      }
      if (id_ != 0L) {
        output.writeInt64(7, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      for (int i = 0; i < courses_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, courses_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < sports_.size(); i++) {
          dataSize += computeStringSizeNoTag(sports_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getSportsList().size();
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.homvee.grpc.service.msgs.GRPCMsg.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.homvee.grpc.service.msgs.GRPCMsg.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.homvee.grpc.Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.homvee.grpc.Student)
        com.homvee.grpc.service.msgs.GRPCMsg.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Student_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.homvee.grpc.service.msgs.GRPCMsg.Student.class, com.homvee.grpc.service.msgs.GRPCMsg.Student.Builder.class);
      }

      // Construct using com.homvee.grpc.service.msgs.GRPCMsg.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getCoursesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        if (coursesBuilder_ == null) {
          courses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          coursesBuilder_.clear();
        }
        sports_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Student_descriptor;
      }

      public com.homvee.grpc.service.msgs.GRPCMsg.Student getDefaultInstanceForType() {
        return com.homvee.grpc.service.msgs.GRPCMsg.Student.getDefaultInstance();
      }

      public com.homvee.grpc.service.msgs.GRPCMsg.Student build() {
        com.homvee.grpc.service.msgs.GRPCMsg.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.homvee.grpc.service.msgs.GRPCMsg.Student buildPartial() {
        com.homvee.grpc.service.msgs.GRPCMsg.Student result = new com.homvee.grpc.service.msgs.GRPCMsg.Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.name_ = name_;
        if (coursesBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            courses_ = java.util.Collections.unmodifiableList(courses_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.courses_ = courses_;
        } else {
          result.courses_ = coursesBuilder_.build();
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          sports_ = sports_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.sports_ = sports_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.homvee.grpc.service.msgs.GRPCMsg.Student) {
          return mergeFrom((com.homvee.grpc.service.msgs.GRPCMsg.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.homvee.grpc.service.msgs.GRPCMsg.Student other) {
        if (other == com.homvee.grpc.service.msgs.GRPCMsg.Student.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (coursesBuilder_ == null) {
          if (!other.courses_.isEmpty()) {
            if (courses_.isEmpty()) {
              courses_ = other.courses_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureCoursesIsMutable();
              courses_.addAll(other.courses_);
            }
            onChanged();
          }
        } else {
          if (!other.courses_.isEmpty()) {
            if (coursesBuilder_.isEmpty()) {
              coursesBuilder_.dispose();
              coursesBuilder_ = null;
              courses_ = other.courses_;
              bitField0_ = (bitField0_ & ~0x00000004);
              coursesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getCoursesFieldBuilder() : null;
            } else {
              coursesBuilder_.addAllMessages(other.courses_);
            }
          }
        }
        if (!other.sports_.isEmpty()) {
          if (sports_.isEmpty()) {
            sports_ = other.sports_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureSportsIsMutable();
            sports_.addAll(other.sports_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.homvee.grpc.service.msgs.GRPCMsg.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.homvee.grpc.service.msgs.GRPCMsg.Student) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>optional int64 id = 7;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 7;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 7;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.homvee.grpc.service.msgs.GRPCMsg.Course> courses_ =
        java.util.Collections.emptyList();
      private void ensureCoursesIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          courses_ = new java.util.ArrayList<com.homvee.grpc.service.msgs.GRPCMsg.Course>(courses_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.homvee.grpc.service.msgs.GRPCMsg.Course, com.homvee.grpc.service.msgs.GRPCMsg.Course.Builder, com.homvee.grpc.service.msgs.GRPCMsg.CourseOrBuilder> coursesBuilder_;

      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public java.util.List<com.homvee.grpc.service.msgs.GRPCMsg.Course> getCoursesList() {
        if (coursesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(courses_);
        } else {
          return coursesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public int getCoursesCount() {
        if (coursesBuilder_ == null) {
          return courses_.size();
        } else {
          return coursesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public com.homvee.grpc.service.msgs.GRPCMsg.Course getCourses(int index) {
        if (coursesBuilder_ == null) {
          return courses_.get(index);
        } else {
          return coursesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public Builder setCourses(
          int index, com.homvee.grpc.service.msgs.GRPCMsg.Course value) {
        if (coursesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoursesIsMutable();
          courses_.set(index, value);
          onChanged();
        } else {
          coursesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public Builder setCourses(
          int index, com.homvee.grpc.service.msgs.GRPCMsg.Course.Builder builderForValue) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.set(index, builderForValue.build());
          onChanged();
        } else {
          coursesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public Builder addCourses(com.homvee.grpc.service.msgs.GRPCMsg.Course value) {
        if (coursesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoursesIsMutable();
          courses_.add(value);
          onChanged();
        } else {
          coursesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public Builder addCourses(
          int index, com.homvee.grpc.service.msgs.GRPCMsg.Course value) {
        if (coursesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCoursesIsMutable();
          courses_.add(index, value);
          onChanged();
        } else {
          coursesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public Builder addCourses(
          com.homvee.grpc.service.msgs.GRPCMsg.Course.Builder builderForValue) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.add(builderForValue.build());
          onChanged();
        } else {
          coursesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public Builder addCourses(
          int index, com.homvee.grpc.service.msgs.GRPCMsg.Course.Builder builderForValue) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.add(index, builderForValue.build());
          onChanged();
        } else {
          coursesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public Builder addAllCourses(
          java.lang.Iterable<? extends com.homvee.grpc.service.msgs.GRPCMsg.Course> values) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, courses_);
          onChanged();
        } else {
          coursesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public Builder clearCourses() {
        if (coursesBuilder_ == null) {
          courses_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          coursesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public Builder removeCourses(int index) {
        if (coursesBuilder_ == null) {
          ensureCoursesIsMutable();
          courses_.remove(index);
          onChanged();
        } else {
          coursesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public com.homvee.grpc.service.msgs.GRPCMsg.Course.Builder getCoursesBuilder(
          int index) {
        return getCoursesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public com.homvee.grpc.service.msgs.GRPCMsg.CourseOrBuilder getCoursesOrBuilder(
          int index) {
        if (coursesBuilder_ == null) {
          return courses_.get(index);  } else {
          return coursesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public java.util.List<? extends com.homvee.grpc.service.msgs.GRPCMsg.CourseOrBuilder> 
           getCoursesOrBuilderList() {
        if (coursesBuilder_ != null) {
          return coursesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(courses_);
        }
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public com.homvee.grpc.service.msgs.GRPCMsg.Course.Builder addCoursesBuilder() {
        return getCoursesFieldBuilder().addBuilder(
            com.homvee.grpc.service.msgs.GRPCMsg.Course.getDefaultInstance());
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public com.homvee.grpc.service.msgs.GRPCMsg.Course.Builder addCoursesBuilder(
          int index) {
        return getCoursesFieldBuilder().addBuilder(
            index, com.homvee.grpc.service.msgs.GRPCMsg.Course.getDefaultInstance());
      }
      /**
       * <code>repeated .com.homvee.grpc.Course courses = 2;</code>
       */
      public java.util.List<com.homvee.grpc.service.msgs.GRPCMsg.Course.Builder> 
           getCoursesBuilderList() {
        return getCoursesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.homvee.grpc.service.msgs.GRPCMsg.Course, com.homvee.grpc.service.msgs.GRPCMsg.Course.Builder, com.homvee.grpc.service.msgs.GRPCMsg.CourseOrBuilder> 
          getCoursesFieldBuilder() {
        if (coursesBuilder_ == null) {
          coursesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.homvee.grpc.service.msgs.GRPCMsg.Course, com.homvee.grpc.service.msgs.GRPCMsg.Course.Builder, com.homvee.grpc.service.msgs.GRPCMsg.CourseOrBuilder>(
                  courses_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          courses_ = null;
        }
        return coursesBuilder_;
      }

      private com.google.protobuf.LazyStringList sports_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureSportsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          sports_ = new com.google.protobuf.LazyStringArrayList(sports_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string sports = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getSportsList() {
        return sports_.getUnmodifiableView();
      }
      /**
       * <code>repeated string sports = 3;</code>
       */
      public int getSportsCount() {
        return sports_.size();
      }
      /**
       * <code>repeated string sports = 3;</code>
       */
      public java.lang.String getSports(int index) {
        return sports_.get(index);
      }
      /**
       * <code>repeated string sports = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSportsBytes(int index) {
        return sports_.getByteString(index);
      }
      /**
       * <code>repeated string sports = 3;</code>
       */
      public Builder setSports(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSportsIsMutable();
        sports_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sports = 3;</code>
       */
      public Builder addSports(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureSportsIsMutable();
        sports_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sports = 3;</code>
       */
      public Builder addAllSports(
          java.lang.Iterable<java.lang.String> values) {
        ensureSportsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sports_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sports = 3;</code>
       */
      public Builder clearSports() {
        sports_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string sports = 3;</code>
       */
      public Builder addSportsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureSportsIsMutable();
        sports_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.homvee.grpc.Student)
    }

    // @@protoc_insertion_point(class_scope:com.homvee.grpc.Student)
    private static final com.homvee.grpc.service.msgs.GRPCMsg.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.homvee.grpc.service.msgs.GRPCMsg.Student();
    }

    public static com.homvee.grpc.service.msgs.GRPCMsg.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Student(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    public com.homvee.grpc.service.msgs.GRPCMsg.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CourseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.homvee.grpc.Course)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 id = 9;</code>
     */
    long getId();

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional int32 score = 10;</code>
     */
    int getScore();
  }
  /**
   * Protobuf type {@code com.homvee.grpc.Course}
   */
  public  static final class Course extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.homvee.grpc.Course)
      CourseOrBuilder {
    // Use Course.newBuilder() to construct.
    private Course(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Course() {
      id_ = 0L;
      name_ = "";
      score_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Course(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 72: {

              id_ = input.readInt64();
              break;
            }
            case 80: {

              score_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Course_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Course_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.homvee.grpc.service.msgs.GRPCMsg.Course.class, com.homvee.grpc.service.msgs.GRPCMsg.Course.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 9;
    private long id_;
    /**
     * <code>optional int64 id = 9;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 10;
    private int score_;
    /**
     * <code>optional int32 score = 10;</code>
     */
    public int getScore() {
      return score_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (id_ != 0L) {
        output.writeInt64(9, id_);
      }
      if (score_ != 0) {
        output.writeInt32(10, score_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, id_);
      }
      if (score_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, score_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.homvee.grpc.service.msgs.GRPCMsg.Course parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Course parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Course parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Course parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Course parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Course parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Course parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Course parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Course parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.homvee.grpc.service.msgs.GRPCMsg.Course parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.homvee.grpc.service.msgs.GRPCMsg.Course prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.homvee.grpc.Course}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.homvee.grpc.Course)
        com.homvee.grpc.service.msgs.GRPCMsg.CourseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Course_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Course_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.homvee.grpc.service.msgs.GRPCMsg.Course.class, com.homvee.grpc.service.msgs.GRPCMsg.Course.Builder.class);
      }

      // Construct using com.homvee.grpc.service.msgs.GRPCMsg.Course.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0L;

        name_ = "";

        score_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.homvee.grpc.service.msgs.GRPCMsg.internal_static_com_homvee_grpc_Course_descriptor;
      }

      public com.homvee.grpc.service.msgs.GRPCMsg.Course getDefaultInstanceForType() {
        return com.homvee.grpc.service.msgs.GRPCMsg.Course.getDefaultInstance();
      }

      public com.homvee.grpc.service.msgs.GRPCMsg.Course build() {
        com.homvee.grpc.service.msgs.GRPCMsg.Course result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.homvee.grpc.service.msgs.GRPCMsg.Course buildPartial() {
        com.homvee.grpc.service.msgs.GRPCMsg.Course result = new com.homvee.grpc.service.msgs.GRPCMsg.Course(this);
        result.id_ = id_;
        result.name_ = name_;
        result.score_ = score_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.homvee.grpc.service.msgs.GRPCMsg.Course) {
          return mergeFrom((com.homvee.grpc.service.msgs.GRPCMsg.Course)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.homvee.grpc.service.msgs.GRPCMsg.Course other) {
        if (other == com.homvee.grpc.service.msgs.GRPCMsg.Course.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getScore() != 0) {
          setScore(other.getScore());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.homvee.grpc.service.msgs.GRPCMsg.Course parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.homvee.grpc.service.msgs.GRPCMsg.Course) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>optional int64 id = 9;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional int64 id = 9;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 id = 9;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int score_ ;
      /**
       * <code>optional int32 score = 10;</code>
       */
      public int getScore() {
        return score_;
      }
      /**
       * <code>optional int32 score = 10;</code>
       */
      public Builder setScore(int value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 score = 10;</code>
       */
      public Builder clearScore() {
        
        score_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:com.homvee.grpc.Course)
    }

    // @@protoc_insertion_point(class_scope:com.homvee.grpc.Course)
    private static final com.homvee.grpc.service.msgs.GRPCMsg.Course DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.homvee.grpc.service.msgs.GRPCMsg.Course();
    }

    public static com.homvee.grpc.service.msgs.GRPCMsg.Course getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Course>
        PARSER = new com.google.protobuf.AbstractParser<Course>() {
      public Course parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Course(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Course> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Course> getParserForType() {
      return PARSER;
    }

    public com.homvee.grpc.service.msgs.GRPCMsg.Course getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_homvee_grpc_Teacher_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_homvee_grpc_Teacher_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_homvee_grpc_Teacher_CourseTcherEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_homvee_grpc_Teacher_CourseTcherEntry_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_homvee_grpc_Student_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_homvee_grpc_Student_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_homvee_grpc_Course_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_homvee_grpc_Course_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rGRPCMsg.proto\022\017com.homvee.grpc\"\245\002\n\007Tea" +
      "cher\022\n\n\002id\030  \001(\003\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\005 " +
      "\001(\005\022\016\n\006salary\030\006 \001(\002\022*\n\010students\030\002 \003(\0132\030." +
      "com.homvee.grpc.Student\022>\n\013courseTcher\030\013" +
      " \003(\0132).com.homvee.grpc.Teacher.CourseTch" +
      "erEntry\032K\n\020CourseTcherEntry\022\013\n\003key\030\001 \001(\t" +
      "\022&\n\005value\030\002 \001(\0132\027.com.homvee.grpc.Course" +
      ":\0028\001\"*\n\006Gender\022\n\n\006UNKOWN\020\000\022\010\n\004MALE\020\001\022\n\n\006" +
      "FEMALE\020\002\"]\n\007Student\022\n\n\002id\030\007 \001(\003\022\014\n\004name\030" +
      "\001 \001(\t\022(\n\007courses\030\002 \003(\0132\027.com.homvee.grpc",
      ".Course\022\016\n\006sports\030\003 \003(\t\"1\n\006Course\022\n\n\002id\030" +
      "\t \001(\003\022\014\n\004name\030\001 \001(\t\022\r\n\005score\030\n \001(\005B\036\n\034co" +
      "m.homvee.grpc.service.msgsb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_homvee_grpc_Teacher_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_homvee_grpc_Teacher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_homvee_grpc_Teacher_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "Salary", "Students", "CourseTcher", });
    internal_static_com_homvee_grpc_Teacher_CourseTcherEntry_descriptor =
      internal_static_com_homvee_grpc_Teacher_descriptor.getNestedTypes().get(0);
    internal_static_com_homvee_grpc_Teacher_CourseTcherEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_homvee_grpc_Teacher_CourseTcherEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_homvee_grpc_Student_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_homvee_grpc_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_homvee_grpc_Student_descriptor,
        new java.lang.String[] { "Id", "Name", "Courses", "Sports", });
    internal_static_com_homvee_grpc_Course_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_homvee_grpc_Course_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_homvee_grpc_Course_descriptor,
        new java.lang.String[] { "Id", "Name", "Score", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
